CREATE  TABLE `watt_node_logs` (
  `serial_num` VARCHAR(64) NOT NULL ,
  `device_num` INT NOT NULL ,
  `time_in_utc` TIMESTAMP NOT NULL ,
  `error` INT NOT NULL ,
  `low_alarm` DECIMAL(12,4) NULL ,
  `high_alarm` DECIMAL(12,4) NULL,
  `energy_sum_kwh` DECIMAL(12,4) NULL,
  `energy_pos_sum_kwh` DECIMAL(12,4) NULL,
  `energy_sum_nr_kwh` DECIMAL(12,4) NULL,
`energy_pos_sum_nr_kwh` DECIMAL(12,4) NULL,
`power_sum_w` DECIMAL(12,4) NULL,
`power_a_w` DECIMAL(12,4) NULL,
`power_b_w` DECIMAL(12,4) NULL,
`power_c_w` DECIMAL(12,4) NULL,
`volts_avg_ln_v` DECIMAL(12,4) NULL,
`volts_phase_a_v` DECIMAL(12,4) NULL,
`volts_phase_b_v` DECIMAL(12,4) NULL,
`volts_phase_c_v` DECIMAL(12,4) NULL,
`volts_avg_ll_v` DECIMAL(12,4) NULL,
`volts_ab_v` DECIMAL(12,4) NULL,
`volts_bc_v` DECIMAL(12,4) NULL,
`volts_ac_v` DECIMAL(12,4) NULL,
`frequency_hz` DECIMAL(12,4) NULL,
`energy_phase_a_kwh` DECIMAL(12,4) NULL,
`energy_phase_b_kwh` DECIMAL(12,4) NULL,
`energy_phase_c_kwh` DECIMAL(12,4) NULL,
`energy_pos_phase_a_kwh` DECIMAL(12,4) NULL,
`energy_pos_phase_b_kwh` DECIMAL(12,4) NULL,
`energy_pos_phase_c_kwh` DECIMAL(12,4) NULL,
`energy_neg_sum_kwh` DECIMAL(12,4) NULL,
`energy_neg_sum_nr_kwh` DECIMAL(12,4) NULL,
`energy_neg_a_kwh` DECIMAL(12,4) NULL,
`energy_neg_b_kwh` DECIMAL(12,4) NULL,
`energy_neg_c_kwh` DECIMAL(12,4) NULL,
`energy_reactive_sum_kwh` DECIMAL(12,4) NULL,
`energy_reactive_phase_a_kwh` DECIMAL(12,4) NULL,
`energy_reactive_phase_b_kwh` DECIMAL(12,4) NULL,
`energy_reactive_phase_c_kwh` DECIMAL(12,4) NULL,
`energy_apparent_sum_kwh` DECIMAL(12,4) NULL,
`energy_apparent_phase_a_kwh` DECIMAL(12,4) NULL,
`energy_apparent_phase_b_kwh` DECIMAL(12,4) NULL,
`energy_apparent_phase_c_kwh` DECIMAL(12,4) NULL,
`power_factor_average` DECIMAL(12,4) NULL,
`power_factor_phase_a` DECIMAL(12,4) NULL,
`power_factor_phase_b` DECIMAL(12,4) NULL,
`power_factor_phase_c` DECIMAL(12,4) NULL,
`power_reactive_sum_var`  DECIMAL(12,4) NULL,
`power_reactive_phase_a_var` DECIMAL(12,4) NULL,
`power_reactive_phase_b_var` DECIMAL(12,4) NULL,
`power_reactive_phase_c_var` DECIMAL(12,4) NULL,
`power_apparent_sum_va` DECIMAL(12,4) NULL,
`power_apparent_phase_a_va` DECIMAL(12,4) NULL,
`power_apparent_phase_b_va` DECIMAL(12,4) NULL,
`power_apparent_phase_c_va` DECIMAL(12,4) NULL,
`current_phase_a_a` DECIMAL(12,4) NULL,
`current_phase_b_a` DECIMAL(12,4) NULL,
`current_phase_c_a` DECIMAL(12,4) NULL,
`demand_w` DECIMAL(12,4) NULL,
`demand_min_w`  DECIMAL(12,4) NULL,
`demand_max_w` DECIMAL(12,4) NULL,
`demand_apparent_w`  DECIMAL(12,4) NULL,
`created_at` DATETIME NULL,
`updated_at` DATETIME NULL,
  PRIMARY KEY (`serial_num`, `device_num`, `time_in_utc`, `error`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;